### ISSUE TITLE
macOS: go movetime / depth

### ISSUE THREAD

**Issue by twoplan** [ratosh/pirarucu#179] opened 2019-07-10 17:26 UTC
I ran some test positions. Your engine seems not to support the uci commands **go movetime x** or **go depth y**. In both cases Pirarucu answers instantly.

```
Starting engine /Users/max/chess/Pirarucu/pirarucu-3.07 ...
>> uci
<< Initialized in 406 ms
<< Handling setoption threads 1
<< id name Pirarucu v3.0.7
<< id author Raoni Campos
<< option name Hash type spin default 256 min 1 max 8192
<< option name PawnHash type spin default 32 min 1 max 1024
<< option name Threads type spin default 1 min 1 max 128
<< uciok
>> setoption name Hash value 128
>> setoption name Contempt value 0
>> setoption name Threads value 1
>> setoption name Cores value 1
>> setoption name Max CPUs value 1

Pos 1
1kr5/3n4/q3p2p/p2n2p1/PppB1P2/5BP1/1P2Q2P/3R2K1 w - - bm f5; id "STS(v1.0) Undermine.001"; c0 "f5=10, Be5+=2, Bf2=3, Bg4=2"; c7 "f5 Be5+ Bf2 Bg4"; c8 "10 2 3 2"; c9 "f4f5 d4e5 d4f2 f3g4";

2019-07-10T19:11:54.669945 >> isready
2019-07-10T19:11:54.670043 << Handling setoption Hash 128
2019-07-10T19:11:54.749147 << Handling setoption Contempt 0
2019-07-10T19:11:54.749227 << Setting Contempt with value 0
2019-07-10T19:11:54.750022 << java.lang.NoSuchFieldException: Contempt
2019-07-10T19:11:54.750185 << at java.lang.Class.getDeclaredField(Class.java:2070)
2019-07-10T19:11:54.750287 << at pirarucu.util.PlatformSpecific.applyConfig(PlatformSpecific.kt:82)
2019-07-10T19:11:54.750368 << at pirarucu.uci.InputHandler.setOption(InputHandler.kt:60)
2019-07-10T19:11:54.750435 << at pirarucu.uci.UciInput.process(UciInput.kt:25)
2019-07-10T19:11:54.750489 << at pirarucu.MainKt.main(Main.kt:66)
2019-07-10T19:11:54.750530 << Handling setoption Threads 1
2019-07-10T19:11:54.750762 << Handling setoption Cores 1
2019-07-10T19:11:54.750814 << Setting Cores with value 1
2019-07-10T19:11:54.750875 << java.lang.NoSuchFieldException: Cores
2019-07-10T19:11:54.750957 << at java.lang.Class.getDeclaredField(Class.java:2070)
2019-07-10T19:11:54.751053 << at pirarucu.util.PlatformSpecific.applyConfig(PlatformSpecific.kt:82)
2019-07-10T19:11:54.751138 << at pirarucu.uci.InputHandler.setOption(InputHandler.kt:60)
2019-07-10T19:11:54.751220 << at pirarucu.uci.UciInput.process(UciInput.kt:25)
2019-07-10T19:11:54.751272 << at pirarucu.MainKt.main(Main.kt:66)
2019-07-10T19:11:54.751436 << Handling setoption Max value
2019-07-10T19:11:54.751598 << java.lang.NumberFormatException: For input string: "value"
2019-07-10T19:11:54.751789 << at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
2019-07-10T19:11:54.751895 << at java.lang.Integer.parseInt(Integer.java:580)
2019-07-10T19:11:54.751987 << at java.lang.Integer.parseInt(Integer.java:615)
2019-07-10T19:11:54.752074 << at pirarucu.uci.InputHandler.setOption(InputHandler.kt:60)
2019-07-10T19:11:54.752142 << at pirarucu.uci.UciInput.process(UciInput.kt:25)
2019-07-10T19:11:54.752193 << at pirarucu.MainKt.main(Main.kt:66)
2019-07-10T19:11:54.752216 << readyok
2019-07-10T19:11:54.752232 >> ucinewgame
2019-07-10T19:11:54.752247 >> position fen 1kr5/3n4/q3p2p/p2n2p1/PppB1P2/5BP1/1P2Q2P/3R2K1 w - - 0 1
2019-07-10T19:11:54.752262 >> go movetime 200
2019-07-10T19:11:54.784073 << info depth 1 time 7 score cp 20 nps 9857 nodes 69 pv f4g5
2019-07-10T19:11:54.784143 << info hashfull 0
2019-07-10T19:11:54.784166 << bestmove f4g5
Engine best move is not one of the solution moves??

Total points for this theme so far : 0/10
```

```
2019-07-10T19:16:23.009077 >> go depth 6
2019-07-10T19:16:23.044666 << info depth 1 time 9 score cp 20 nps 7666 nodes 69 pv f4g5
2019-07-10T19:16:23.044745 << info hashfull 0
2019-07-10T19:16:23.044768 << bestmove f4g5
Engine best move is not one of the solution moves??

Total points for this theme so far : 0/10
```

Is this a macOS issue, or didn't you implement go movetime/depth?

**Comment by ratosh** [comment] 2019-07-10 21:11
Duplicate of #176

**Comment by ratosh** [comment] 2019-12-29 21:13
New release fixed this issue, please test:
https://github.com/ratosh/pirarucu/releases/tag/v3.2.4

**Closed** 2020-01-01 10:29 UTC
